config/routes.rb
Despsingles::Application.routes.draw do
  root "pages#home"
  get "about" => "pages#about"
  get "love" => "pages#love"
  get "thoughts" => "pages#thoughts"
  get "prayers" => "pages#prayers"
  get "contact" => "pages#contact"

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end

  def love
  end
  
  def thoughts
  end

  def prayers
  end

  def contact
  end 
  	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "DESPERATESingl.es", root_path, class: "navbar-brand" %>
  </div>  

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Love", love_path %></li>
      <li><%= link_to "Thoughts", thoughts_path %></li>
      <li><%= link_to "Prayers", prayers_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
   </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desperate Singles ;(</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<!doctype html>
<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>

<style>
html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, font, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td {margin:0; padding:0; border:0; outline:0; font-size:100%; vertical-align:baseline; background:transparent;} body {line-height: 1;}ol, ul{list-style:none;} blockquote, q{quotes:none;} blockquote:before, blockquote:after, q:before, q:after{content:'';content:none;} :focus{outline:0;} ins{text-decoration:none;} del{text-decoration:line-through;} table{border-collapse:collapse; border-spacing:0;}

/*MAIN*/
body { 
	font-size: 1.05em;
	line-height: 1.25em;
	font-family:'Oswald', sans-serif;
	color: #808080;
}



}

img {

	width: 100%;

}

header {

	background: #fff;
	width: 100%;
	height: 76px;
	position: fixed;
	top: 0;
	left: 0;
	border-bottom: 4px solid #4C9CF1;
	z-index: 100;
	font-family:'Oswald', sans-serif;

}

tim{
		font-family:'Oswald', sans-serif;
		color: black;
		font-size: 60px;
		float: left;
		padding: 20px;
}

nav {

	float: right;
	padding: 20px;	

}
a:link    {color:black;}
a:visited {color:black;}
a:hover   {color:red;}
a:active  {color:black;}

a.ex1:hover,a.ex1:active {color:red;}
a.ex2:hover,a.ex2:active {font-size:150%;}
}

ul {

	list-style: none;

}

li {

	display: inline-block;
	float: left;
	padding: 10px

}

h1 {

	font-size: 24px;
	color: #black;
	line-height: 1.15em;
	margin: 20px 0 ;
	text-align: center;

}

h2 {

	font-size: 14px;
	color: #black;
	margin: 20px 0 ;
	margin-top: -30px;
	text-align: center;

}

p {

	line-height: 1.45em;
	margin-bottom: 20px;

}


</style>

	

<body>

</body>


<nav>


<h1><br><br><br><br><br><br><br><br><br><br>Hold tight, Desperados- <br><br><h2>We're working on bringing romantic relief to you shortly.</h2></p>
</h1>


<p></p>

<p></p>

</section>

</body>
<a><div style="height:100%; width:100%;">
<img src="http://i.imgur.com/SzIQgBD.png" style="position:absolute; float:right; right:0px; bottom:0px; z-index:2;">
</div></a>

<footer><nav>

<a href="#" id="menu-icon"></a>

<ul>

<li><a href="http://www.desperatesingl.es/home" style="text-decoration: none" class="current">Home</a></li>
<li><a href="http://www.desperatesingl.es/about" style="text-decoration: none">About</a></li>
<li><a href="http://www.desperatesingl.es/love" style="text-decoration: none">Love</a></li>
<li><a href="http://www.desperatesingl.es/thoughts" style="text-decoration: none">Thoughts</a></li>
<li><a href="http://www.desperatesingl.es/contact" style="text-decoration: none">Contact</a></li>

</ul>
</nav><dslogo>DESPERATEsingl.es</dslogo><h4>Romantic relief for the broken-hearted.</h4></footer>
</html>

app/views/pages/contact.html.erb
<!doctype HTML>

<h1>C O N T A C T</h1>
<br>
<blockquote><h3>"Just kidding, it's this page that needs help. TIM, MAKE IT LOOK PRETTY" --Mallory (again)</h3></blockquote>

</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<head> 	<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  	   	<link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>


<style>

header{
	max-width::100%;
	text-align: center;
	margin-top: 50px;
	font-size: 80px;
	font-family:'Oswald', sans-serif;
	color: rgba(255, 255, 255, 0.75);
	position: relative;
	}	

h4{
  max-width::100%;
  text-align: left;
  padding-left: 20px;
  float: left;
  font-size: 10px;
  font-family: 'Shadows Into Light', cursive;
  color: white;
  margin-top: 65px;
  margin-left: -345px;
}

dslogo{
    font-family:'Oswald', sans-serif;
    color: white;
    font-size: 45px;
    float: left;
    margin-left: 20px;
    margin-top: 10px;
}

html {
    position: relative;
    min-height: 100%;
}
body {


}
footer {
    position: absolute;
    left: 0;
    bottom: 0;
    height: 100px;
    width: 100%;
    background-color: black;
    font-family:'Oswald', sans-serif;
    color: white;
}

Body{
	margin: 0 0 100px; /* bottom = footer height */
	background:url("http://i.imgur.com/he4QxLD.jpg") no-repeat;
	background-size: 100%;
	align: center;
}

h2{
	font-size: 13px;
	text-align: center;
	margin-left: -145px;
	font-family: 'Josefin Sans', sans-serif;

}

h3{
	font-size: 13px;
	text-align: center;
	margin-left: 180px;
	margin-top: -24px;
	font-family: 'Josefin Sans', sans-serif;

}

 button {
 	height: 10px
 }

 input{
  display: inline-block;
  background-color: rgba(255, 255, 255, 0.25);
  position: relative;
  font-family:'Oswald', sans-serif;
  text-align: center;
  font-size: 24px;
  padding: 10px;
    }
    input[type="submit"]   {
            background: rgba(255, 0, 0, 0.25);
            color: white;
            font-family: 'Oswald', sans-serif;
            position: relative;
            border-radius: 10px;

}

input,select,textarea { /* These three elements round up all the input types */
    display: block; 
    margin: 0 auto; 
    position: left;
}

nav {
	float: right;
	padding: 20px;	
	font-family:'Oswald', sans-serif;

}
a:link    {color:white;}
a:visited {color:white;}
a:hover   {color:red;}
a:active  {color:white;}

a.ex1:hover,a.ex1:active {color:red;}
a.ex2:hover,a.ex2:active {font-size:150%;}
}

ul {
	list-style: none;
}

li {
	display: inline-block;
	float: left;
	padding: 10px
}
</style>

</head>

<title>DESPERATESINGL.ES</title>
<header>DESPERATE<b>singl.es</b></header>
<body>
	<br>
	<br>
	<br>
	<input type="login" placeholder="USERNAME">
	<br>
	<br>
	<input type="password" placeholder="PASSWORD">
	<h2>Forgot Login?</h2> <h3>Sign Up</h3>

<input type="submit" placeholder="SIGN IN">  </div>
</body>

<footer><nav>

<a href="#" id="menu-icon"></a>

<ul>

<li><a href="http://www.desperatesingl.es/home" style="text-decoration: none" class="current">Home</a></li>
<li><a href="http://www.desperatesingl.es/about" style="text-decoration: none">About</a></li>
<li><a href="http://www.desperatesingl.es/love" style="text-decoration: none">Love</a></li>
<li><a href="http://www.desperatesingl.es/thoughts" style="text-decoration: none">Thoughts</a></li>
<li><a href="http://www.desperatesingl.es/contact" style="text-decoration: none">Contact</a></li>

</ul>
</nav><dslogo>DESPERATEsingl.es</dslogo><h4>Romantic relief for the broken-hearted.</h4></footer>


</html>

app/views/pages/love.html.erb
<!doctype HTML>


<h1>Love</h1>

<blockquote><h3> "What's luv got to do widdit?" --Fat Joe </h3></blockquote>

app/views/pages/prayers.html.erb
<!doctype HTML>

<h1>Prayers</h1>

<blockquote><h3> "Gurl, you need some help." --Mallory Brewer </h3></blockquote>


<footer><nav>

<a href="#" id="menu-icon"></a>

<ul>

<li><a href="http://www.desperatesingl.es" style="text-decoration: none" class="current">Home</a></li>
<li><a href="http://www.desperatesingl.es/about" style="text-decoration: none">About</a></li>
<li><a href="http://www.desperatesingl.es/love" style="text-decoration: none">Love</a></li>
<li><a href="http://www.desperatesingl.es/thoughts" style="text-decoration: none">Thoughts</a></li>
<li><a href="http://www.desperatesingl.es/contact" style="text-decoration: none">Contact</a></li>

</ul>
</nav><dslogo>DESPERATEsingl.es</dslogo><h4>Romantic relief for the broken-hearted.</h4></footer>


</html>

app/views/pages/thoughts.html.erb
<!doctype HTML>

<h1>T H O U G H T S</h1>
<br>
<blockquote><h3>"There is no desperation like desperation itself" --FDR, on the Great Depression of your dating life</h3></blockquote>

<footer><nav>

<a href="#" id="menu-icon"></a>

<ul>

<li><a href="http://www.desperatesingl.es/home" style="text-decoration: none" class="current">Home</a></li>
<li><a href="http://www.desperatesingl.es/about" style="text-decoration: none">About</a></li>
<li><a href="http://www.desperatesingl.es/love" style="text-decoration: none">Love</a></li>
<li><a href="http://www.desperatesingl.es/thoughts" style="text-decoration: none">Thoughts</a></li>
<li><a href="http://www.desperatesingl.es/contact" style="text-decoration: none">Contact</a></li>

</ul>
</html>